[package]
name = "rust_jni"
version = "0.3.0"
edition = "2021"

[dependencies]
jni = "0.21"
# smlm-hawk-core = {path = "../../hawk/smlm-hawk-core"}
smlm-hawk-core = "0.2"

[lib]
crate-type = ["cdylib"]